clients/urls.py
from django.urls import path

from .views import (
    DetailPlantings,
    client_index,
    coopdetailPlantings,
    detail_planting,
    export_formation_to_pdf,
    export_planting_xls,
    plants_par_section,
    projet,
    detail_proj,
    localisation,
    detail_coop,
    # chart,
    prod_coop,
    parcelle_coop,
    localisation_coop,
    section_coop,
    sous_section_coop,
    planting_coop, formations,
    detail_formation,
    export_prod_xls,
    export_parcelle_xls,
    export_prods_to_pdf,
    export_parcelles_to_pdf,
    Plantings, pepiniere, producteur, parcelle, production, planting, prod_coop_par_campagne,
    # export_plant_xls,
    # export_formation_xls,
    # export_prods_to_pdf,
    # export_parcelles_to_pdf,
    # producteursPDF
)

app_name = 'clients'

urlpatterns = [
    # path('', connexion, name='connexion'),
    # path('logout', loggout, name='logout'),
    path('index/', client_index, name='dashboard'), 
    path('projets/', projet, name='projets'),
    path('formation/<int:id>', formations, name='formations'),
    path('formation/<int:id>/<int:_id>', detail_formation, name='formation'),
    path('producteurs/<int:id>', prod_coop, name='prod_coop'),
    path('parcelles/<int:id>', parcelle_coop, name='parcelle_coop'),
    path('sections/<int:id>', section_coop, name='section_coop'),
    path('sous_sections/<int:id>', sous_section_coop, name='sous_section_coop'),
    path('planting/<int:id>', planting_coop, name='planting_coop'),
    path('coordonnes/<int:id>', localisation_coop, name='localisation_coop'),
    path('localisation/', localisation, name='localisation'),
    path('Plantings/', Plantings, name='Plantings'),
    path('DetailPlantings/', DetailPlantings, name='DetailPlantings'),
    path('coopdetailPlantings/<int:id>', coopdetailPlantings, name='coopdetailPlantings'),
    path('plants_par_section/<int:id>', plants_par_section, name='plants_par_section'),
    path('prod_coop_par_campagne/<int:id>', prod_coop_par_campagne, name='prod_coop_par_campagne'),

    # path('site_pepinieres/', site_pepinieres, name='site_pepinieres'),
    # path('coop_pepiniere/<int:id>', coop_pepiniere, name='coop_pepiniere'),
    path('detail_proj/<int:id>', detail_proj, name='detail_proj'),
    path('detail_coop/<int:id>', detail_coop, name='detail_coop'),
    # #Charts
    # path('Stats_coop/', Stats_coop, name='stats_coop'),
    # path('Stats_semences/', Stats_semences, name='stats_semences'),
    # path('Production_plan/', Production_plan, name='production_plan'),
    # path('plants_coop/<int:id>', plants_coop, name='plants_coop'),
    # path('semences_coop/<int:id>', semences_coop, name='semences_coop'),
    # path('chart/<int:id>', chart, name='chart'),
    #
    # #Export to Excel
    path('cooperative/<int:id>/producteurs/xls/', export_prod_xls, name='export_prod_xls'),
    # # path('sections/xls/', export_section_xls, name='export_section_xls'),
    # # path('sous_sections/xls/', export_sous_section_xls, name='export_sous_section_xls'),
    path('cooperative/<int:id>/parcelles/xls/', export_parcelle_xls, name='export_parcelle_xls'),
    # path('cooperative/<int:id>/plants/xls/', export_plant_xls, name='export_plant_xls'),
    # path('cooperative/<int:id>/formations/xls/', export_formation_xls, name='export_formation_xls'),
    #
    # # Export Données EN PDF
    path('producteurs/pdf/<str:id>', export_prods_to_pdf, name='export_prods_to_pdf'),
    # path('producteurs/pdf/<int:id>', producteursPDF, name='prods_to_pdf'),
    path('parcelles/pdf/<int:id>', export_parcelles_to_pdf, name='export_parcelles_to_pdf'),

    path('pepinieres/', pepiniere, name='pepinieres'),

    path('export_formation_to_pdf/<int:id>', export_formation_to_pdf, name='export_formation_to_pdf'),

    path('producteurs/', producteur, name='producteurs'),
    path('parcelles/', parcelle, name='parcelles'),
    path('productions/', production, name='productions'),
    path('plantings/', planting, name='plantings'),
    path('plantings/<str:code>', detail_planting, name='suivi_planting'),
    path('export_planting_xls/', export_planting_xls, name='export_planting_xls'),
]

cooperatives/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static

from .views import (
    RemplaceSave,
    changeSection,
    contactProd,
    coop_dashboard,
    add_section,
    add_sous_section,
    createDetailmonitoring,
    createDetailplanting,
    createEspecemonitoring,
    createParcelle,
    createPlanting,
    createProducteurs,
    deleteEspece,
    deletes,
    edit_formatoin,
    edit_monitoring,
    edit_monitoring_view,
    edit_parcelle,
    edit_product,
    edit_productor,
    edit_section,
    edit_sous_section,
    endremplaceSave,
    espece_monitoring_view,
    esrempla_monitoring_view,
    export_formation_to_pdf,
    export_parcelles_to_pdf,
    formationSave,
    getListParcForcoop,
    getMonitoringForcoop,
    getProducteursForcoop,
    monitoring_form_view,
    monitoringCreate,
    monitoringSave,
    parcelle_update,
    parcelleSave,
    participant_delete,
    plantingSave,
    producteurSave,
    producteurs,
    production,
    # cooperative,
    prod_update,
    prod_delete,
    parcelles,
    parcelle_delete,
    # planting,
    # planting_update,
    formation,
    detail_formation,
    AddPlantingView,
    export_planting_xls,
    # use Ajax and jquery request
    my_section,
    export_producteur_csv,
    # PlantingDelete,
    export_prods_to_pdf,
    export_prod_xls,
    export_parcelle_xls,
    export_plant_xls, Editformation,
    production_delete,
    production_update,
    productionSave,
    rempend_monitoring_view,
    remplacement_monitoring_view,
    saveParticipant,
    tranning,
    update_formation, delete_section, export_section_xls,
    update_section,
    update_sous_section,
    export_sous_section_xls, export_formation_xls, delete_sous_section, ParcellesMapView, parcelle_list, ReceptionView,
    folium_map, PlantingList, detail_planting, coopdetailPlantings, CoopPlantings, getParcelleCoop, map_by_cooperative,
    updateMonitoring,
    updateProducteur,
    # delete_sous_section, export_sous_section_xls, export_formation_xls, my_parcelles, ParcellesView,
    # load_section
)

app_name='cooperatives'

urlpatterns = [
    # Patient
    # path('cooperative/<int:id>', cooperative, name='cooperative'),
    path('producteur/<str:code>/modifier', prod_update, name='modifier'),
    path('producteur/<str:code>/supprimer', prod_delete, name='del_producteur'),
    # path('parcelle/<int:id>', parcelle_delete, name='del_parcelle'),
    path('parcelle/<str:code>/modifier', edit_parcelle, name='edit_parcelle'),
    path('parcelle/<str:code>/supprimer', parcelle_delete, name='parcelle_delete'),
    path('section/<int:id>/delete/supprimer', delete_section, name='delete_section'),
  
    path('sous_section/<int:id>/supprimer', delete_sous_section, name='delete_sous_section'),
    path('dashboard/', coop_dashboard, name='dashboard'),
    path('sections/', add_section, name='section'),
    path('sous_sections/', add_sous_section, name='sous_sections'),
    path('formation/', formation, name='formations'),
    path('Editformation/<int:id>', Editformation, name='Editformation'),
    path('formation/<int:id>', detail_formation, name='formation'),
    path('producteurs/', producteurs, name='producteurs'),
    path('parcelles/', parcelles, name='parcelles'),
    #path('my_parcelles/', my_parcelles, name='my_parcelles'),
    # path('plantings/', planting, name='planting'),
    path('planting_coop/', CoopPlantings, name='CoopPlantings'),
    path('coopdetailPlantings/', coopdetailPlantings, name='coopdetailPlantings'),
    path('plantings/<str:code>/', detail_planting, name='suivi_planting'),
    path('add_planting/', AddPlantingView.as_view(), name='add_planting'),
# detail_planting
    # path('planting/<int:pk>', PlantingDelete.as_view(), name='planting-delete'),
    path('folium_map/', folium_map, name='folium_map'),

    #get Ajax Data
    # path('parcelles/data', ParcellesView.as_view(), name="parcelles_data"),
    path('parcelle_list/', parcelle_list, name="parcelle_list"),
    path('parcelles_list/', ParcellesMapView.as_view(), name="parcelle_list"),

    #path('my-section/', my_section, name='my_section'),
    # path('ajax/load-section/', load_section, name='ajax_load_section'),

    #Exportation de Données En Excel
    # path('export/csv/', export_producteur_csv, name='export_producteur_csv'),
    path('producteurs/xls/', export_prod_xls, name='export_prod_xls'),
    path('sections/xls/', export_section_xls, name='export_section_xls'),
    path('sous_sections/xls/', export_sous_section_xls, name='export_sous_section_xls'),
    path('parcelles/xls/', export_parcelle_xls, name='export_parcelle_xls'),
    path('plants/xls/', export_plant_xls, name='export_plant_xls'),
    path('formations/xls/', export_formation_xls, name='export_formation_xls'),
    path('plantings/xls/', export_planting_xls, name='export_planting_xls'),

    #Export Données EN PDF
    path('producteurs/pdf/', export_prods_to_pdf, name='export_prods_to_pdf'),
    path('parcelles/pdf/', export_parcelles_to_pdf, name='export_parcelles_to_pdf'),


    path('parcelleCoop/<str:code>/', getParcelleCoop, name="parcelleCoop"),

    #route des parcelles par cooperative
    path('map_by_cooperative', map_by_cooperative, name="map_by_cooperative"),
    ######################################monitoring
    path('edit_monitoring_view/<str:code>/', edit_monitoring_view, name="edit_monitoring_view"),
    path('edit_monitoring', edit_monitoring, name="edit_monitoring"),
    path('edit_productor', edit_productor, name="edit_productor"),
    path('edit_formatoin/<int:id>', edit_formatoin, name="edit_formatoin"),
    path('update_formation', update_formation, name="update_formation"),
    path('parcelle_update', parcelle_update, name="parcelle_update"),
    path('edit_section/<int:id>', edit_section, name="edit_section"),
    path('update_section/', update_section, name='update_section'),
    path('edit_sous_section/<int:id>', edit_sous_section, name="edit_sous_section"),
    path('sous_section/', update_sous_section, name='update_sous_section'),
    path('monitoringSave/', monitoringSave, name='monitoringSave'),
    path('espece_monitoring_view/<str:code>', espece_monitoring_view, name='espece_monitoring_view'),
    path('plantingSave/', plantingSave, name='plantingSave'),
    path('producteurSave/', producteurSave, name='producteurSave'),
    path('parcelleSave/', parcelleSave, name='parcelleSave'),
    path('tranning/<int:id>', tranning, name='tranning'),
    path('saveParticipant/', saveParticipant, name='saveParticipant'),
    path('deletes/', deletes, name='deletes'),
    path('participant_delete/<int:id>', participant_delete, name='participant_delete'),
    path('formationSave/', formationSave, name='formationSave'),
    path('export_formation_to_pdf/<int:id>/', export_formation_to_pdf, name='export_formation_to_pdf'),
    path('changeSection/', changeSection, name='selectSection'),
    path('contactProd/', contactProd, name='contactProd'),
    path('remplacement_monitoring_view/<str:code>/', remplacement_monitoring_view, name='remplacement_monitoring_view'),
    path('RemplaceSave/', RemplaceSave, name='RemplaceSave'),
    path('endremplaceSave/', endremplaceSave, name='endremplaceSave'),
    path('esrempla_monitoring_view/<str:code>/', esrempla_monitoring_view, name='esrempla_monitoring_view'),
    path('rempend_monitoring_view/<str:code>/', rempend_monitoring_view, name='rempend_monitoring_view'),
    path('monitoring_form_view/<str:code>/', monitoring_form_view, name='monitoring_form_view'),
    path('deleteEspece/<str:code>/', deleteEspece, name='deleteEspece'),
    path('production/', production, name="productions"),
    path('productionSave/', productionSave, name="productionSave"),
    path('edit_product/<str:code>/', edit_product, name='edit_product'),
    path('production_delete/<str:code>/', production_delete, name='production_delete'),
    path('production_update/', production_update, name="production_update"),








   #####################API URL FLUTTER#######################

    ###PRODUCTEUR
    path('apiProdListCoop/<int:id>/',getProducteursForcoop,name='apilist_prod'),
    path('apiCreateProd/',createProducteurs,name='apicreate_prod'),
    path('apiUpdateProd/<int:id>/', updateProducteur, name='apiup_prod'),

    ###PARCELLE
    path('apiParcListCoop/',getListParcForcoop,name='apilist_parc'),
    path('apiCreateParc/',createParcelle,name='apicreate_parc'),

    ###PLANTING
    path('apiCreatePlant/',createPlanting,name='apicreate_plant'),
    path('apiCreatedetailPlant/',createDetailplanting,name='apicreate_detailplant'),

    ###MONITORING
    path('apiListMonitoring/',getMonitoringForcoop,name='apiget_moni'),
    path('apiCreateMonitoring/',monitoringCreate,name='apicreate_moni'),
    path('apiCreatedetailMonitoring/',createDetailmonitoring,name='apicreate_detailmoni'),
    path('apiCreateMonitoringespece/',createEspecemonitoring,name='apicreate_moniespece'),
    path('apiUpdateMonitoringespece/',updateMonitoring,name='apiupdate_moniespece'),

   ################################################################## 
]

traceability/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clients/', include('clients.urls')),
    path('cooperatives/', include('cooperatives.urls')),
    path('', include('parametres.urls')),
    # path('api/v1/', include('djoser.urls')),
    # path('api/v1/', include('djoser.urls.authtoken')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cooperatives/templates/cooperatives/formations/insert.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap4 %}
{{ form.media.css }}
{{ form.media.js }}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
{% block title %}
{{ instance.libelle }} |
{% endblock %}
{% block content %}
    <div id="wrapper">
            <!-- Navigation -->
            {% include 'cooperatives/coop_nav.html' %}
            <div id="page-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <h3 class="page-header"> <a href="{% url 'cooperatives:formation' intitule.id %}"><i class="fa fa-arrow-left"></i></a>  Enregistrer une formation</h3>
                        </div>
                        <!-- /.col-lg-12 -->
                    </div>
              
                    <!-- /.row -->
                    <div class="row">

                        <div class="col-md-4 " style="border-right: solid;">
                            <h3>PARTICIPANT</h3>
                            <form id="addUser" action="">
                                {% csrf_token %}
                              <div class="form-group">
                                <input class="form-control" onblur="globalproduct('{% url 'cooperatives:contactProd' %}')" type="text" list="nom" id="id_nom" name="nom" placeholder="Nom et prénoms" required>
                                <span class="nom_error text-danger"></span>
                                <datalist id="nom" >
                                    {% for prod in producteurs %}
                                        <option value="{{ prod.nom }} {{ prod.prenoms }}">{{ prod.nom }} {{ prod.prenoms }}</option>
                                    {% endfor %}
                                </datalist>
                              </div>
                              <div class="form-group">
                                {% render_field participantForm.contact id="contact" maxlength="10" class="form-control CONTACT" pattern="\d*" placeholder="contact du Participant" %}
                              </div>
                              <button class="btn btn-primary form-control" onclick="saveParticipant('{% url 'cooperatives:saveParticipant' %}')"> Ajouter Participant </button>
                            </form>
                        </div>

                        <div class="col-md-8">
                            <form id="form" action="">
                                {% csrf_token %}
                                <h3 style="margin: 0px;">Info de la formation</h3>
                                <hr style="margin: 0px 0px 8px 0px;">

                                <div class="row">
<!-- /.row -->  
                                    <div class="col-md-6 " >
                                        <div class="form-group">
                                            {% render_field formationForm.formateur class="form-control" placeholder="Nom et prénoms du formateur" %}
                                            <span class="formateur_error text-danger"></span>
                                        <!--  <input class="form-control" type="text" name="formation" placeholder="Nom et prénoms du formateur" required>-->  
                                          </div>

                                    </div>
                                    <div class="col-md-6 " >
                                        <div class="form-group">
                                           <select class="form-control" name="campagne" id="">
                                            <option value="" selected>--Select Campagne--</option>
                                               {% for campagne in campagnes %}
                                                 <option value="{{campagne.id}}">{{campagne.titre}}</option>
                                               {% endfor %}                                              
                                           </select>                                      
                                           <span class="campagne_error text-danger"></span>
                                          </div>
                                    </div>                        

                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">   
                                            <label for="">Structure du formateur</label> 
                                            {% render_field formationForm.structureformateur  class="form-control"   %}

                                            <!-- <textarea name="" id="" cols="20" placeholder="Note du formateur" rows="2"></textarea>-->
                                          </div>
                                    </div>

                                    <div class="col-md-6">
                                        <div class="form-group">   
                                            <label for="">Niveau du formateur</label> 
                                            {% render_field formationForm.niveauformateur  class="form-control"   %}

                                            <!-- <textarea name="" id="" cols="20" placeholder="Note du formateur" rows="2"></textarea>-->
                                          </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-4" >
                                        <div class="form-group">
                                            <label for="">Date debut</label>
                                             <input class="form-control" type="hidden" name="intitule" value="{{intitule.id}}" >
                                            {% render_field formationForm.debut type="date" class="form-control"  %}
                                            <span class="debut_error text-danger"></span>
                                          </div>
                                    </div> 
                                    <div class="col-md-4" >
                                        <div class="form-group">
                                            <label for="">Date fin</label>
                                            {% render_field formationForm.fin type="date" class="form-control"  %}
                                            <span class="fin_error text-danger"></span>
                                          </div>

                                    </div> 
                                    <div class="col-md-4" >
                                        <div class="form-group">   
                                            <label for="">Critère de satisfaction</label> 
                                            {% render_field formationForm.critere  class="form-control"   %}

                                            <!-- <textarea name="" id="" cols="20" placeholder="Note du formateur" rows="2"></textarea>-->
                                          </div>

                                    </div> 
                                </div>
                               
                                <div class="row">
                                    <div class="col-md-8" >
                                        <div class="form-group">    
                                            {% render_field formationForm.note_formateur  class="form-control" placeholder="Mot du formateur" rows="3" cols="20"  %}

                                            <!-- <textarea name="" id="" cols="20" placeholder="Note du formateur" rows="2"></textarea>-->
                                          </div>

                                    </div> 

                                </div>
                                <hr style="margin: 0px 0px 8px 0px;">
                                <h5 style="margin: 0px;">Liste des Participants</h5>
                                <table id="userTable" class="table table-bordered border-primary" >
                                    <thead class="table-primary" style="background-color: skyblue;">
                                        <tr>
                                          
                                            <th>Nom et prénoms</th>
                                            <th>Telephone</th>
                                            <th>Action</th> 
                                        </tr>
                                    </thead>
                                    <tbody>


                                        {% for participant in participants %}

                                        <tr id="participant-{{participant.id}}"> 
                                         <td id="col0">
                                                <input type="text" class="form-control" value="{{participant.nom}}" name="nom" readonly >
                                                <input class="form-control" type="hidden" name="participant" value="{{participant.id}}" >
                                            </td> 
                                            <td id="col1">
                                                
                                                <input type="text" class="form-control" {% if not participant.contact %} value="" {% else %} value="{{participant.contact}}" {% endif %}   name="contact" readonly >
                                            </td> 
                                        
                                            <td id="col2 " class="text-center"> 
                                                <a href="#"  onclick="delete_semence('{% url 'cooperatives:participant_delete' participant.id %}' )" style="padding: 0px;" class="btn btn-danger">
                                                    <i class="fa fa-trash fa-fw"></i>
                                                </a>
                                            </td>
                                           
                                        </tr>

                                        {% endfor %}                                    
                                                                                                                                                      
                                        
                                        
                                    </tbody>  
                           
                                </table> 
                                    
                                       <!-- <td><button type="button" class="btn btn-sm btn-info" onclick="addRows()">Add</button></td>
                                        <td><button type="button" class="btn btn-sm btn-danger" onclick="deleteRows()">Remore</button></td>-->
                                       <button onclick="SaveAndRedirect('{% url 'cooperatives:formationSave' %}')" class="btn btn-sm btn-success " style="float: right;">Enregistrer la formation</button>
                                  
                                <br>
                                <br>

                            </form>

                        </div>
                        
                     
                
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
                
            </div>
            <!-- /#page-wrapper -->
        </div>
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="{% static 'lib/jquery.formatter.min.js' %}"></script>
        

        <script src="{% static 'js/function.js' %}"></script>
{% endblock %}