clients/urls.py
from django.urls import path

from .views import (
    DetailPlantings,
    client_index,
    coopdetailPlantings,
    detail_planting,
    export_formation_to_pdf,
    export_planting_xls,
    plants_par_section,
    projet,
    detail_proj,
    localisation,
    detail_coop,
    # chart,
    prod_coop,
    parcelle_coop,
    localisation_coop,
    section_coop,
    sous_section_coop,
    planting_coop, formations,
    detail_formation,
    export_prod_xls,
    export_parcelle_xls,
    export_prods_to_pdf,
    export_parcelles_to_pdf,
    Plantings, pepiniere, producteur, parcelle, production, planting, prod_coop_par_campagne,
    # export_plant_xls,
    # export_formation_xls,
    # export_prods_to_pdf,
    # export_parcelles_to_pdf,
    # producteursPDF
)

app_name = 'clients'

urlpatterns = [
    # path('', connexion, name='connexion'),
    # path('logout', loggout, name='logout'),
    path('index/', client_index, name='dashboard'), 
    path('projets/', projet, name='projets'),
    path('formation/<int:id>', formations, name='formations'),
    path('formation/<int:id>/<int:_id>', detail_formation, name='formation'),
    path('producteurs/<int:id>', prod_coop, name='prod_coop'),
    path('parcelles/<int:id>', parcelle_coop, name='parcelle_coop'),
    path('sections/<int:id>', section_coop, name='section_coop'),
    path('sous_sections/<int:id>', sous_section_coop, name='sous_section_coop'),
    path('planting/<int:id>', planting_coop, name='planting_coop'),
    path('coordonnes/<int:id>', localisation_coop, name='localisation_coop'),
    path('localisation/', localisation, name='localisation'),
    path('Plantings/', Plantings, name='Plantings'),
    path('DetailPlantings/', DetailPlantings, name='DetailPlantings'),
    path('coopdetailPlantings/<int:id>', coopdetailPlantings, name='coopdetailPlantings'),
    path('plants_par_section/<int:id>', plants_par_section, name='plants_par_section'),
    path('prod_coop_par_campagne/<int:id>', prod_coop_par_campagne, name='prod_coop_par_campagne'),

    # path('site_pepinieres/', site_pepinieres, name='site_pepinieres'),
    # path('coop_pepiniere/<int:id>', coop_pepiniere, name='coop_pepiniere'),
    path('detail_proj/<int:id>', detail_proj, name='detail_proj'),
    path('detail_coop/<int:id>', detail_coop, name='detail_coop'),
    # #Charts
    # path('Stats_coop/', Stats_coop, name='stats_coop'),
    # path('Stats_semences/', Stats_semences, name='stats_semences'),
    # path('Production_plan/', Production_plan, name='production_plan'),
    # path('plants_coop/<int:id>', plants_coop, name='plants_coop'),
    # path('semences_coop/<int:id>', semences_coop, name='semences_coop'),
    # path('chart/<int:id>', chart, name='chart'),
    #
    # #Export to Excel
    path('cooperative/<int:id>/producteurs/xls/', export_prod_xls, name='export_prod_xls'),
    # # path('sections/xls/', export_section_xls, name='export_section_xls'),
    # # path('sous_sections/xls/', export_sous_section_xls, name='export_sous_section_xls'),
    path('cooperative/<int:id>/parcelles/xls/', export_parcelle_xls, name='export_parcelle_xls'),
    # path('cooperative/<int:id>/plants/xls/', export_plant_xls, name='export_plant_xls'),
    # path('cooperative/<int:id>/formations/xls/', export_formation_xls, name='export_formation_xls'),
    #
    # # Export Données EN PDF
    path('producteurs/pdf/<str:id>', export_prods_to_pdf, name='export_prods_to_pdf'),
    # path('producteurs/pdf/<int:id>', producteursPDF, name='prods_to_pdf'),
    path('parcelles/pdf/<int:id>', export_parcelles_to_pdf, name='export_parcelles_to_pdf'),

    path('pepinieres/', pepiniere, name='pepinieres'),

    path('export_formation_to_pdf/<int:id>', export_formation_to_pdf, name='export_formation_to_pdf'),

    path('producteurs/', producteur, name='producteurs'),
    path('parcelles/', parcelle, name='parcelles'),
    path('productions/', production, name='productions'),
    path('plantings/', planting, name='plantings'),
    path('plantings/<str:code>', detail_planting, name='suivi_planting'),
    path('export_planting_xls/', export_planting_xls, name='export_planting_xls'),
]

cooperatives/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static

from .views import (
    RemplaceSave,
    changeSection,
    contactProd,
    coop_dashboard,
    add_section,
    add_sous_section,
    createDetailmonitoring,
    createDetailplanting,
    createEspecemonitoring,
    createParcelle,
    createPlanting,
    createProducteurs,
    deleteEspece,
    deletes,
    edit_formatoin,
    edit_monitoring,
    edit_monitoring_view,
    edit_parcelle,
    edit_product,
    edit_productor,
    edit_section,
    edit_sous_section,
    endremplaceSave,
    espece_monitoring_view,
    esrempla_monitoring_view,
    export_formation_to_pdf,
    export_parcelles_to_pdf,
    formationSave,
    getListParcForcoop,
    getMonitoringForcoop,
    getProducteursForcoop,
    monitoring_form_view,
    monitoringCreate,
    monitoringSave,
    parcelle_update,
    parcelleSave,
    participant_delete,
    plantingSave,
    producteurSave,
    producteurs,
    production,
    # cooperative,
    prod_update,
    prod_delete,
    parcelles,
    parcelle_delete,
    # planting,
    # planting_update,
    formation,
    detail_formation,
    AddPlantingView,
    export_planting_xls,
    # use Ajax and jquery request
    my_section,
    export_producteur_csv,
    # PlantingDelete,
    export_prods_to_pdf,
    export_prod_xls,
    export_parcelle_xls,
    export_plant_xls, Editformation,
    production_delete,
    production_update,
    productionSave,
    rempend_monitoring_view,
    remplacement_monitoring_view,
    saveParticipant,
    tranning,
    update_formation, delete_section, export_section_xls,
    update_section,
    update_sous_section,
    export_sous_section_xls, export_formation_xls, delete_sous_section, ParcellesMapView, parcelle_list, ReceptionView,
    folium_map, PlantingList, detail_planting, coopdetailPlantings, CoopPlantings, getParcelleCoop, map_by_cooperative,
    updateMonitoring,
    updateProducteur,
    # delete_sous_section, export_sous_section_xls, export_formation_xls, my_parcelles, ParcellesView,
    # load_section
)

app_name='cooperatives'

urlpatterns = [
    # Patient
    # path('cooperative/<int:id>', cooperative, name='cooperative'),
    path('producteur/<str:code>/modifier', prod_update, name='modifier'),
    path('producteur/<str:code>/supprimer', prod_delete, name='del_producteur'),
    # path('parcelle/<int:id>', parcelle_delete, name='del_parcelle'),
    path('parcelle/<str:code>/modifier', edit_parcelle, name='edit_parcelle'),
    path('parcelle/<str:code>/supprimer', parcelle_delete, name='parcelle_delete'),
    path('section/<int:id>/delete/supprimer', delete_section, name='delete_section'),
  
    path('sous_section/<int:id>/supprimer', delete_sous_section, name='delete_sous_section'),
    path('dashboard/', coop_dashboard, name='dashboard'),
    path('sections/', add_section, name='section'),
    path('sous_sections/', add_sous_section, name='sous_sections'),
    path('formation/', formation, name='formations'),
    path('Editformation/<int:id>', Editformation, name='Editformation'),
    path('formation/<int:id>', detail_formation, name='formation'),
    path('producteurs/', producteurs, name='producteurs'),
    path('parcelles/', parcelles, name='parcelles'),
    #path('my_parcelles/', my_parcelles, name='my_parcelles'),
    # path('plantings/', planting, name='planting'),
    path('planting_coop/', CoopPlantings, name='CoopPlantings'),
    path('coopdetailPlantings/', coopdetailPlantings, name='coopdetailPlantings'),
    path('plantings/<str:code>/', detail_planting, name='suivi_planting'),
    path('add_planting/', AddPlantingView.as_view(), name='add_planting'),
# detail_planting
    # path('planting/<int:pk>', PlantingDelete.as_view(), name='planting-delete'),
    path('folium_map/', folium_map, name='folium_map'),

    #get Ajax Data
    # path('parcelles/data', ParcellesView.as_view(), name="parcelles_data"),
    path('parcelle_list/', parcelle_list, name="parcelle_list"),
    path('parcelles_list/', ParcellesMapView.as_view(), name="parcelle_list"),

    #path('my-section/', my_section, name='my_section'),
    # path('ajax/load-section/', load_section, name='ajax_load_section'),

    #Exportation de Données En Excel
    # path('export/csv/', export_producteur_csv, name='export_producteur_csv'),
    path('producteurs/xls/', export_prod_xls, name='export_prod_xls'),
    path('sections/xls/', export_section_xls, name='export_section_xls'),
    path('sous_sections/xls/', export_sous_section_xls, name='export_sous_section_xls'),
    path('parcelles/xls/', export_parcelle_xls, name='export_parcelle_xls'),
    path('plants/xls/', export_plant_xls, name='export_plant_xls'),
    path('formations/xls/', export_formation_xls, name='export_formation_xls'),
    path('plantings/xls/', export_planting_xls, name='export_planting_xls'),

    #Export Données EN PDF
    path('producteurs/pdf/', export_prods_to_pdf, name='export_prods_to_pdf'),
    path('parcelles/pdf/', export_parcelles_to_pdf, name='export_parcelles_to_pdf'),


    path('parcelleCoop/<str:code>/', getParcelleCoop, name="parcelleCoop"),

    #route des parcelles par cooperative
    path('map_by_cooperative', map_by_cooperative, name="map_by_cooperative"),
    ######################################monitoring
    path('edit_monitoring_view/<str:code>/', edit_monitoring_view, name="edit_monitoring_view"),
    path('edit_monitoring', edit_monitoring, name="edit_monitoring"),
    path('edit_productor', edit_productor, name="edit_productor"),
    path('edit_formatoin/<int:id>', edit_formatoin, name="edit_formatoin"),
    path('update_formation', update_formation, name="update_formation"),
    path('parcelle_update', parcelle_update, name="parcelle_update"),
    path('edit_section/<int:id>', edit_section, name="edit_section"),
    path('update_section/', update_section, name='update_section'),
    path('edit_sous_section/<int:id>', edit_sous_section, name="edit_sous_section"),
    path('sous_section/', update_sous_section, name='update_sous_section'),
    path('monitoringSave/', monitoringSave, name='monitoringSave'),
    path('espece_monitoring_view/<str:code>', espece_monitoring_view, name='espece_monitoring_view'),
    path('plantingSave/', plantingSave, name='plantingSave'),
    path('producteurSave/', producteurSave, name='producteurSave'),
    path('parcelleSave/', parcelleSave, name='parcelleSave'),
    path('tranning/<int:id>', tranning, name='tranning'),
    path('saveParticipant/', saveParticipant, name='saveParticipant'),
    path('deletes/', deletes, name='deletes'),
    path('participant_delete/<int:id>', participant_delete, name='participant_delete'),
    path('formationSave/', formationSave, name='formationSave'),
    path('export_formation_to_pdf/<int:id>/', export_formation_to_pdf, name='export_formation_to_pdf'),
    path('changeSection/', changeSection, name='selectSection'),
    path('contactProd/', contactProd, name='contactProd'),
    path('remplacement_monitoring_view/<str:code>/', remplacement_monitoring_view, name='remplacement_monitoring_view'),
    path('RemplaceSave/', RemplaceSave, name='RemplaceSave'),
    path('endremplaceSave/', endremplaceSave, name='endremplaceSave'),
    path('esrempla_monitoring_view/<str:code>/', esrempla_monitoring_view, name='esrempla_monitoring_view'),
    path('rempend_monitoring_view/<str:code>/', rempend_monitoring_view, name='rempend_monitoring_view'),
    path('monitoring_form_view/<str:code>/', monitoring_form_view, name='monitoring_form_view'),
    path('deleteEspece/<str:code>/', deleteEspece, name='deleteEspece'),
    path('production/', production, name="productions"),
    path('productionSave/', productionSave, name="productionSave"),
    path('edit_product/<str:code>/', edit_product, name='edit_product'),
    path('production_delete/<str:code>/', production_delete, name='production_delete'),
    path('production_update/', production_update, name="production_update"),








   #####################API URL FLUTTER#######################

    ###PRODUCTEUR
    path('apiProdListCoop/<int:id>/',getProducteursForcoop,name='apilist_prod'),
    path('apiCreateProd/',createProducteurs,name='apicreate_prod'),
    path('apiUpdateProd/<int:id>/', updateProducteur, name='apiup_prod'),

    ###PARCELLE
    path('apiParcListCoop/',getListParcForcoop,name='apilist_parc'),
    path('apiCreateParc/',createParcelle,name='apicreate_parc'),

    ###PLANTING
    path('apiCreatePlant/',createPlanting,name='apicreate_plant'),
    path('apiCreatedetailPlant/',createDetailplanting,name='apicreate_detailplant'),

    ###MONITORING
    path('apiListMonitoring/',getMonitoringForcoop,name='apiget_moni'),
    path('apiCreateMonitoring/',monitoringCreate,name='apicreate_moni'),
    path('apiCreatedetailMonitoring/',createDetailmonitoring,name='apicreate_detailmoni'),
    path('apiCreateMonitoringespece/',createEspecemonitoring,name='apicreate_moniespece'),
    path('apiUpdateMonitoringespece/',updateMonitoring,name='apiupdate_moniespece'),

   ################################################################## 
]

traceability/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clients/', include('clients.urls')),
    path('cooperatives/', include('cooperatives.urls')),
    path('', include('parametres.urls')),
    # path('api/v1/', include('djoser.urls')),
    # path('api/v1/', include('djoser.urls.authtoken')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

clients/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os
import time
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
import datetime

from django.utils.safestring import mark_safe
#from django_countries.fields import CountryField

ANNEES = []
for r in range(2019, (datetime.datetime.now().year+1)):
    ANNEES.append((r,r))

def upload_logo_site(self, filename):
    # verification de l'extension
    real_name, extension = os.path.splitext(filename)
    name = str(int(time.time())) + extension
    return "logos/" + self.sigle + ".jpeg"

class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    sigle = models.CharField(max_length=500, verbose_name="NOM / SIGLE")
    contacts = models.CharField(max_length=50, verbose_name="CONTACTS")
    libelle = models.CharField(max_length=250, verbose_name="NOM")
    pays = models.CharField(max_length=250, verbose_name="NOM",default="")
    adresse = models.CharField(max_length=250, verbose_name="ADRESSE", blank=True)
    telephone1 = models.CharField(max_length=50)
    telephone2 = models.CharField(max_length=50, blank=True, null=True)
    email = models.EmailField(max_length=120, blank=True, verbose_name="ADRESSE EMAIL")
    siteweb = models.CharField(max_length=120, blank=True, verbose_name="SITE WEB")
    logo = models.ImageField(verbose_name="Logo", upload_to=upload_logo_site, blank=True)
    objects = models.Manager()

    def __str__(self):
        return '%s' % (self.libelle)

    def save(self, force_insert=False, force_update=False):
        self.sigle = self.sigle.upper()
        self.libelle = self.libelle.upper()
        super(Client, self).save(force_insert, force_update)

    class Meta:
        verbose_name_plural = "CLIENTS"
        verbose_name = "client"

    def Logo(self):
        if self.logo:
            return mark_safe('<img src="%s" style="width: 60px; height:50px;" />' % self.logo.url)
        else:
            return "Aucun Logo"

    Logo.short_description = 'Logo'

# Create your models here.

clients/templates/clients/Coop/client_nav.html
{% load static %}

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'clients:dashboard' %}">PANNEAU D'ADMINISTRATION - {{ cooperative.sigle }}</a>
    </div>

    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <ul class="nav navbar-right navbar-top-links">
        {% if user.is_authenticated %}
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> {{ user.username }} <b class="caret"></b>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out fa-fw"></i> Déconnexion</a>
                    </li>
                </ul>
            </li>
        {% endif %}
    </ul>
    <!-- /.navbar-top-links -->
    {% include 'clients/Coop/client_sidebar.html' %}
</nav>

clients/templates/clients/Coop/client_sidebar.html
{% load static %}
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li>
                <a href="{% url 'clients:detail_coop' cooperative.id %}" {% if activate == "dashboard" %}class="active"{% else %} class="" {% endif %}><i class="fa fa-dashboard fa-fw"></i> DASHBOARD</a>
            </li>
            <li>
                <a href="{% url 'clients:prod_coop' cooperative.id %}" {% if activate == "producteurs" %}class="active"{% else %} class="" {% endif %}><i class="fa fa-users fa-fw"></i> PRODUCTEURS</a>
            </li>
            <li>
                <a href="{% url 'clients:parcelle_coop' cooperative.id %}" {% if activate == "parcelles" %}class="active"{% else %} class="" {% endif %}><i class="glyphicon glyphicon-grain"></i> PARCELLES</a>
            </li>
            <li>
                <a href="{% url 'clients:planting_coop' cooperative.id %}" {% if activate == "plantings" %}class="active"{% else %} class="" {% endif %}><i class="glyphicon glyphicon-tree-deciduous"></i> SUIVI PARCELLES</a>
            </li>
            <li>
                <a href="{% url 'clients:formations' cooperative.id %}" {% if activate == "formations" %}class="active"{% else %} class="" {% endif %}><i class="fa fa-list-ul fa-fw"></i> FORMATIONS</a>
            </li>
        </ul>
    </div>
</div>

clients/templates/clients/Coop/coop_parcelle.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap4 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
{% block title %}
    Parcelles |
{% endblock %}
{% block content %}
    <div id="wrapper">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    {% if user.is_authenticated %}
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'accueil' %}">{{ cooperative.sigle }} / {{ cooperative.get_projet_values }}</a>
        </div>
    {% endif %}

    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>

    <ul class="nav navbar-right navbar-top-links">
        {% if user.is_authenticated %}
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> {{ user.username }} <b class="caret"></b>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out fa-fw"></i> Déconnexion</a>
                    </li>
                </ul>
            </li>
        {% endif %}
    </ul>
    <!-- /.navbar-top-links -->
    {% include 'clients/Coop/client_nav.html' %}
</nav>
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">Parcelles - {{ cooperative.sigle }}</h1>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <div class="row">
                    <div class="col-sm-6 offset-3">
                        {% include '_partials/messages_display.html' %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-info">
                            <div class="panel-heading">
                                <a href="{% url 'clients:export_parcelle_xls' cooperative.id %}" class="btn btn-success"><i class="fa fa-file-excel-o fa-fw fa-2x"></i> EXCEL</a>
                                <a href="{% url 'clients:export_parcelles_to_pdf' cooperative.id %}" class="btn btn-danger"><i class="fa fa-file-pdf-o fa-fw fa-2x"></i> PDF</a>
                            </div>
                            <!-- /.panel-heading -->
                            <div class="panel-body" style="font-size: 12px">
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                        <thead>
                                            <tr>
                                                <th class="text-center">CODE</th>
                                                <th class="text-center">PRODUCTEUR</th>
                                                <th class="text-center">SECTION</th>
                                                <th class="text-center">LOCALITE</th>
                                                <th class="text-center">SUPERFICIE (Ha)</th>
                                                <th class="text-center">LON</th>
                                                <th class="text-center">LAT</th>
                                                <th class="text-center">CULTURE</th>


                                            </tr>
                                        </thead>
                                        <tbody class="text-center">
                                            {% for parcelle in coop_parcelles %}
                                                <tr class="odd gradeX text-center">
                                                    {% if parcelle.code %}
                                                        <td class="center"><b>{{ parcelle.code }}</b></td>
                                                    {% else %}
                                                        <td class="center" style="color: red"><b>EN ATTENTE</b></td>
                                                    {% endif %}
                                                    <td class="center"><b>{{ parcelle.producteur }}</b></td>
                                                    <td class="center">{{ parcelle.producteur.section }}</td>
                                                    <td class="center">{{ parcelle.producteur.localite }}</td>
                                                    <td class="center">{{ parcelle.superficie }}</td>
                                                    <td class="center">{{ parcelle.longitude }}</td>
                                                    <td class="center">{{ parcelle.latitude }}</td>
                                                    <td>{{ parcelle.culture|upper }}</td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <!-- /.panel-body -->
                        </div>
                        <!-- /.panel -->
                    </div>
                    <!-- /.col-lg-8 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->

{#            <div class="modal fade"  data-keyboard="false" data-backdrop="static" id="ParcelleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">#}
{#                <div class="modal-dialog modal-lg" role="document">#}
{#                    <div class="modal-content">#}
{#                        <form method="post" enctype="multipart/form-data">#}
{#                            {% csrf_token %}#}
{#                            <div class="modal-header">#}
{#                                <h4 class="modal-title" id="exampleModalLabel" style="font-weight:bold">AJOUTER NOUVELLE PARCELLE</h4>#}
{#                                <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="margin-top: -25px">x</button>#}
{#                            </div>#}
{#                            <div class="model-body">#}
{#                                <div class="col-sm-12">#}
{#                                    {{ parcelleForm.media }}#}
{#                                    <div class="row">#}
{#                                        <div class="col-sm-6">#}
{#                                            <div class="form-group">#}
{#                                                <label>Propriétaire</label>#}
{#                                                {% render_field parcelleForm.producteur class="form-control" %}#}
{#                                                <select name="producteur" placeholder="Producteur" class="form-control" id="id_producteur">#}
{#                                                    {% for prod in producteurs %}#}
{#                                                        <option value="{{ prod.pk }}">{{ prod.code }} {{ prod.nom }} {{ prod.prenoms }}</option>#}
{#                                                    {% endfor %}#}
{#                                                </select>#}
{#                                            </div>#}
{#                                            <div class="form-group">#}
{#                                                <label>Section</label>#}
{#                                                {% render_field parcelleForm.section class="form-control" %}#}
{#                                            </div>#}
{#                                            <div class="form-group">#}
{#                                                <label>Sous Section</label>#}
{#                                                {% render_field parcelleForm.sous_section class="form-control" %}#}
{#                                            </div>#}
{#                                            <div class="row">#}
{#                                                <div class="col-sm-6">#}
{#                                                    <div class="form-group">#}
{#                                                        <label>SUPERFICIE</label>#}
{#                                                        {% render_field parcelleForm.superficie class="form-control" placeholder="Longitude" %}#}
{#                                                    </div>#}
{#                                                </div>#}
{#                                                <div class="col-sm-6">#}
{#                                                    <div class="form-group">#}
{#                                                        <label>ACQUISITION</label>#}
{#                                                        {% render_field parcelleForm.acquisition class="form-control" placeholder="Latitude" %}#}
{#                                                    </div>#}
{#                                                </div>#}
{#                                            </div>#}
{#                                            <div class="form-group">#}
{#                                                <label>LATITUDE</label>#}
{#                                                {% render_field parcelleForm.latitude class="form-control" placeholder="Latitude" %}#}
{#                                            </div>#}
{#                                        </div>#}
{#                                        <div class="col-sm-6">#}
{#                                            <div class="form-group">#}
{#                                                <label>PROJET</label>#}
{#                                                {% render_field parcelleForm.projet class="form-control" placeholder="Acquisition" %}#}
{#                                            </div>#}
{#                                            <div class="form-group">#}
{#                                                <label>CULTURE</label>#}
{#                                                {% render_field parcelleForm.culture class="form-control" placeholder="Culture" %}#}
{#                                            </div>#}
{#                                            <div class="form-group">#}
{#                                                <label>CERTIFICATION</label>#}
{#                                                {% render_field parcelleForm.certification class="form-control" placeholder="Certification" %}#}
{#                                            </div>#}
{#                                            <div class="form-group">#}
{#                                                <label>LONGITUDE</label>#}
{#                                                {% render_field parcelleForm.longitude class="form-control" placeholder="Longitude" %}#}
{#                                            </div>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </div>#}
{#                            </div>#}
{#                            <div class="modal-footer">#}
{#                                <hr />#}
{#                                <Button ID="btnAnnuler" style="font-size:1.7vmin; width:100px" class="btn btn-default"  data-dismiss="modal" >Annuler</Button>#}
{#                                <input type="submit" name="btnValider" value="Valider" id="btnValider" class="btn btn-primary" style="font-size:1.7vmin;width:250px" />#}
{#                            </div>#}
{#                        </form>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
        </div>
    </div>
{% endblock %}