clients/urls.py
from django.urls import path

from .views import (
    DetailPlantings,
    client_index,
    coopdetailPlantings,
    detail_planting,
    export_formation_to_pdf,
    export_planting_xls,
    plants_par_section,
    projet,
    detail_proj,
    localisation,
    detail_coop,
    # chart,
    prod_coop,
    parcelle_coop,
    localisation_coop,
    section_coop,
    sous_section_coop,
    planting_coop, formations,
    detail_formation,
    export_prod_xls,
    export_parcelle_xls,
    export_prods_to_pdf,
    export_parcelles_to_pdf,
    Plantings, pepiniere, producteur, parcelle, production, planting, prod_coop_par_campagne,
    # export_plant_xls,
    # export_formation_xls,
    # export_prods_to_pdf,
    # export_parcelles_to_pdf,
    # producteursPDF
)

app_name = 'clients'

urlpatterns = [
    # path('', connexion, name='connexion'),
    # path('logout', loggout, name='logout'),
    path('index/', client_index, name='dashboard'), 
    path('projets/', projet, name='projets'),
    path('formation/<int:id>', formations, name='formations'),
    path('formation/<int:id>/<int:_id>', detail_formation, name='formation'),
    path('producteurs/<int:id>', prod_coop, name='prod_coop'),
    path('parcelles/<int:id>', parcelle_coop, name='parcelle_coop'),
    path('sections/<int:id>', section_coop, name='section_coop'),
    path('sous_sections/<int:id>', sous_section_coop, name='sous_section_coop'),
    path('planting/<int:id>', planting_coop, name='planting_coop'),
    path('coordonnes/<int:id>', localisation_coop, name='localisation_coop'),
    path('localisation/', localisation, name='localisation'),
    path('Plantings/', Plantings, name='Plantings'),
    path('DetailPlantings/', DetailPlantings, name='DetailPlantings'),
    path('coopdetailPlantings/<int:id>', coopdetailPlantings, name='coopdetailPlantings'),
    path('plants_par_section/<int:id>', plants_par_section, name='plants_par_section'),
    path('prod_coop_par_campagne/<int:id>', prod_coop_par_campagne, name='prod_coop_par_campagne'),

    # path('site_pepinieres/', site_pepinieres, name='site_pepinieres'),
    # path('coop_pepiniere/<int:id>', coop_pepiniere, name='coop_pepiniere'),
    path('detail_proj/<int:id>', detail_proj, name='detail_proj'),
    path('detail_coop/<int:id>', detail_coop, name='detail_coop'),
    # #Charts
    # path('Stats_coop/', Stats_coop, name='stats_coop'),
    # path('Stats_semences/', Stats_semences, name='stats_semences'),
    # path('Production_plan/', Production_plan, name='production_plan'),
    # path('plants_coop/<int:id>', plants_coop, name='plants_coop'),
    # path('semences_coop/<int:id>', semences_coop, name='semences_coop'),
    # path('chart/<int:id>', chart, name='chart'),
    #
    # #Export to Excel
    path('cooperative/<int:id>/producteurs/xls/', export_prod_xls, name='export_prod_xls'),
    # # path('sections/xls/', export_section_xls, name='export_section_xls'),
    # # path('sous_sections/xls/', export_sous_section_xls, name='export_sous_section_xls'),
    path('cooperative/<int:id>/parcelles/xls/', export_parcelle_xls, name='export_parcelle_xls'),
    # path('cooperative/<int:id>/plants/xls/', export_plant_xls, name='export_plant_xls'),
    # path('cooperative/<int:id>/formations/xls/', export_formation_xls, name='export_formation_xls'),
    #
    # # Export Données EN PDF
    path('producteurs/pdf/<str:id>', export_prods_to_pdf, name='export_prods_to_pdf'),
    # path('producteurs/pdf/<int:id>', producteursPDF, name='prods_to_pdf'),
    path('parcelles/pdf/<int:id>', export_parcelles_to_pdf, name='export_parcelles_to_pdf'),

    path('pepinieres/', pepiniere, name='pepinieres'),

    path('export_formation_to_pdf/<int:id>', export_formation_to_pdf, name='export_formation_to_pdf'),

    path('producteurs/', producteur, name='producteurs'),
    path('parcelles/', parcelle, name='parcelles'),
    path('productions/', production, name='productions'),
    path('plantings/', planting, name='plantings'),
    path('plantings/<str:code>', detail_planting, name='suivi_planting'),
    path('export_planting_xls/', export_planting_xls, name='export_planting_xls'),
]

cooperatives/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static

from .views import (
    RemplaceSave,
    changeSection,
    contactProd,
    coop_dashboard,
    add_section,
    add_sous_section,
    createDetailmonitoring,
    createDetailplanting,
    createEspecemonitoring,
    createParcelle,
    createPlanting,
    createProducteurs,
    deleteEspece,
    deletes,
    edit_formatoin,
    edit_monitoring,
    edit_monitoring_view,
    edit_parcelle,
    edit_product,
    edit_productor,
    edit_section,
    edit_sous_section,
    endremplaceSave,
    espece_monitoring_view,
    esrempla_monitoring_view,
    export_formation_to_pdf,
    export_parcelles_to_pdf,
    formationSave,
    getListParcForcoop,
    getMonitoringForcoop,
    getProducteursForcoop,
    monitoring_form_view,
    monitoringCreate,
    monitoringSave,
    parcelle_update,
    parcelleSave,
    participant_delete,
    plantingSave,
    producteurSave,
    producteurs,
    production,
    # cooperative,
    prod_update,
    prod_delete,
    parcelles,
    parcelle_delete,
    # planting,
    # planting_update,
    formation,
    detail_formation,
    AddPlantingView,
    export_planting_xls,
    # use Ajax and jquery request
    my_section,
    export_producteur_csv,
    # PlantingDelete,
    export_prods_to_pdf,
    export_prod_xls,
    export_parcelle_xls,
    export_plant_xls, Editformation,
    production_delete,
    production_update,
    productionSave,
    rempend_monitoring_view,
    remplacement_monitoring_view,
    saveParticipant,
    tranning,
    update_formation, delete_section, export_section_xls,
    update_section,
    update_sous_section,
    export_sous_section_xls, export_formation_xls, delete_sous_section, ParcellesMapView, parcelle_list, ReceptionView,
    folium_map, PlantingList, detail_planting, coopdetailPlantings, CoopPlantings, getParcelleCoop, map_by_cooperative,
    updateMonitoring,
    updateProducteur,
    # delete_sous_section, export_sous_section_xls, export_formation_xls, my_parcelles, ParcellesView,
    # load_section
)

app_name='cooperatives'

urlpatterns = [
    # Patient
    # path('cooperative/<int:id>', cooperative, name='cooperative'),
    path('producteur/<str:code>/modifier', prod_update, name='modifier'),
    path('producteur/<str:code>/supprimer', prod_delete, name='del_producteur'),
    # path('parcelle/<int:id>', parcelle_delete, name='del_parcelle'),
    path('parcelle/<str:code>/modifier', edit_parcelle, name='edit_parcelle'),
    path('parcelle/<str:code>/supprimer', parcelle_delete, name='parcelle_delete'),
    path('section/<int:id>/delete/supprimer', delete_section, name='delete_section'),
  
    path('sous_section/<int:id>/supprimer', delete_sous_section, name='delete_sous_section'),
    path('dashboard/', coop_dashboard, name='dashboard'),
    path('sections/', add_section, name='section'),
    path('sous_sections/', add_sous_section, name='sous_sections'),
    path('formation/', formation, name='formations'),
    path('Editformation/<int:id>', Editformation, name='Editformation'),
    path('formation/<int:id>', detail_formation, name='formation'),
    path('producteurs/', producteurs, name='producteurs'),
    path('parcelles/', parcelles, name='parcelles'),
    #path('my_parcelles/', my_parcelles, name='my_parcelles'),
    # path('plantings/', planting, name='planting'),
    path('planting_coop/', CoopPlantings, name='CoopPlantings'),
    path('coopdetailPlantings/', coopdetailPlantings, name='coopdetailPlantings'),
    path('plantings/<str:code>/', detail_planting, name='suivi_planting'),
    path('add_planting/', AddPlantingView.as_view(), name='add_planting'),
# detail_planting
    # path('planting/<int:pk>', PlantingDelete.as_view(), name='planting-delete'),
    path('folium_map/', folium_map, name='folium_map'),

    #get Ajax Data
    # path('parcelles/data', ParcellesView.as_view(), name="parcelles_data"),
    path('parcelle_list/', parcelle_list, name="parcelle_list"),
    path('parcelles_list/', ParcellesMapView.as_view(), name="parcelle_list"),

    #path('my-section/', my_section, name='my_section'),
    # path('ajax/load-section/', load_section, name='ajax_load_section'),

    #Exportation de Données En Excel
    # path('export/csv/', export_producteur_csv, name='export_producteur_csv'),
    path('producteurs/xls/', export_prod_xls, name='export_prod_xls'),
    path('sections/xls/', export_section_xls, name='export_section_xls'),
    path('sous_sections/xls/', export_sous_section_xls, name='export_sous_section_xls'),
    path('parcelles/xls/', export_parcelle_xls, name='export_parcelle_xls'),
    path('plants/xls/', export_plant_xls, name='export_plant_xls'),
    path('formations/xls/', export_formation_xls, name='export_formation_xls'),
    path('plantings/xls/', export_planting_xls, name='export_planting_xls'),

    #Export Données EN PDF
    path('producteurs/pdf/', export_prods_to_pdf, name='export_prods_to_pdf'),
    path('parcelles/pdf/', export_parcelles_to_pdf, name='export_parcelles_to_pdf'),


    path('parcelleCoop/<str:code>/', getParcelleCoop, name="parcelleCoop"),

    #route des parcelles par cooperative
    path('map_by_cooperative', map_by_cooperative, name="map_by_cooperative"),
    ######################################monitoring
    path('edit_monitoring_view/<str:code>/', edit_monitoring_view, name="edit_monitoring_view"),
    path('edit_monitoring', edit_monitoring, name="edit_monitoring"),
    path('edit_productor', edit_productor, name="edit_productor"),
    path('edit_formatoin/<int:id>', edit_formatoin, name="edit_formatoin"),
    path('update_formation', update_formation, name="update_formation"),
    path('parcelle_update', parcelle_update, name="parcelle_update"),
    path('edit_section/<int:id>', edit_section, name="edit_section"),
    path('update_section/', update_section, name='update_section'),
    path('edit_sous_section/<int:id>', edit_sous_section, name="edit_sous_section"),
    path('sous_section/', update_sous_section, name='update_sous_section'),
    path('monitoringSave/', monitoringSave, name='monitoringSave'),
    path('espece_monitoring_view/<str:code>', espece_monitoring_view, name='espece_monitoring_view'),
    path('plantingSave/', plantingSave, name='plantingSave'),
    path('producteurSave/', producteurSave, name='producteurSave'),
    path('parcelleSave/', parcelleSave, name='parcelleSave'),
    path('tranning/<int:id>', tranning, name='tranning'),
    path('saveParticipant/', saveParticipant, name='saveParticipant'),
    path('deletes/', deletes, name='deletes'),
    path('participant_delete/<int:id>', participant_delete, name='participant_delete'),
    path('formationSave/', formationSave, name='formationSave'),
    path('export_formation_to_pdf/<int:id>/', export_formation_to_pdf, name='export_formation_to_pdf'),
    path('changeSection/', changeSection, name='selectSection'),
    path('contactProd/', contactProd, name='contactProd'),
    path('remplacement_monitoring_view/<str:code>/', remplacement_monitoring_view, name='remplacement_monitoring_view'),
    path('RemplaceSave/', RemplaceSave, name='RemplaceSave'),
    path('endremplaceSave/', endremplaceSave, name='endremplaceSave'),
    path('esrempla_monitoring_view/<str:code>/', esrempla_monitoring_view, name='esrempla_monitoring_view'),
    path('rempend_monitoring_view/<str:code>/', rempend_monitoring_view, name='rempend_monitoring_view'),
    path('monitoring_form_view/<str:code>/', monitoring_form_view, name='monitoring_form_view'),
    path('deleteEspece/<str:code>/', deleteEspece, name='deleteEspece'),
    path('production/', production, name="productions"),
    path('productionSave/', productionSave, name="productionSave"),
    path('edit_product/<str:code>/', edit_product, name='edit_product'),
    path('production_delete/<str:code>/', production_delete, name='production_delete'),
    path('production_update/', production_update, name="production_update"),








   #####################API URL FLUTTER#######################

    ###PRODUCTEUR
    path('apiProdListCoop/<int:id>/',getProducteursForcoop,name='apilist_prod'),
    path('apiCreateProd/',createProducteurs,name='apicreate_prod'),
    path('apiUpdateProd/<int:id>/', updateProducteur, name='apiup_prod'),

    ###PARCELLE
    path('apiParcListCoop/',getListParcForcoop,name='apilist_parc'),
    path('apiCreateParc/',createParcelle,name='apicreate_parc'),

    ###PLANTING
    path('apiCreatePlant/',createPlanting,name='apicreate_plant'),
    path('apiCreatedetailPlant/',createDetailplanting,name='apicreate_detailplant'),

    ###MONITORING
    path('apiListMonitoring/',getMonitoringForcoop,name='apiget_moni'),
    path('apiCreateMonitoring/',monitoringCreate,name='apicreate_moni'),
    path('apiCreatedetailMonitoring/',createDetailmonitoring,name='apicreate_detailmoni'),
    path('apiCreateMonitoringespece/',createEspecemonitoring,name='apicreate_moniespece'),
    path('apiUpdateMonitoringespece/',updateMonitoring,name='apiupdate_moniespece'),

   ################################################################## 
]

traceability/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clients/', include('clients.urls')),
    path('cooperatives/', include('cooperatives.urls')),
    path('', include('parametres.urls')),
    # path('api/v1/', include('djoser.urls')),
    # path('api/v1/', include('djoser.urls.authtoken')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cooperatives/templates/cooperatives/folium_map.html
{% load static %}
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
{#    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">#}
{#    {% include '_partials/css.html' %}#}
    <title>MAP | AGROMAP-Traçability</title>
</head>
<body>
    <div class="container" style="margin-top: 25px">
        <div class="row mt-5">
            <div class="col-md-10 md-offset-1">
                {{ m|safe }}
            </div>
        </div>
    </div>

{#       {% include '_partials/js.html' %}#}
</body>
</html>

cooperatives/templates/cooperatives/parcelle_delete.html
<!DOCTYPE html>
{% load static %}
{% load widget_tweaks %}
{% load bootstrap4 %}
{% bootstrap_messages %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Parheto10">
        <title>Agro - Map | Traçability</title>
        {% include '_partials/css.html' %}
        {% include '_partials/js.html' %}
        <script>
            $(document).ready(function(){
                $("#DeleteParcelleModal").modal('show');
            });
        </script>
    </head>
    <body>
        <div class="modal fade"  data-keyboard="false" data-backdrop="static" id="DeleteParcelleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
                <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="panel panel-red">
                            <div class="panel-heading">
                                {% if parcelle.code %}
                                    <i class="fa fa-trash fa-fw"></i>  SUPPRESSION PARCELLE {{ parcelle.code }} {{ parcelle.producteur }}
                                {% else %}
                                    <i class="fa fa-trash fa-fw"></i>  SUPPRESSION PARCELLE DE {{ parcelle.producteur }}
                                {% endif %}
{#                                <h4 class="modal-title" id="exampleModalLabel" style="font-weight:bold"> <i class="fa fa-close"></i> </h4>#}
                            </div>
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-sm-12 text-center">
                                        {% if parcelle.code %}
                                            <p style="font-size: 22px; font-weight: bold">La Parcelle ({{ parcelle.code }}) - {{ parcelle.producteur.nom }} {{ parcelle.producteur.prenoms }} sera supprimer définitivement,<br /> voulez-vous continuer ?</p>
                                        {% else %}
                                            <p style="font-size: 22px; font-weight: bold">La Parcelle de {{ parcelle.producteur.nom }} {{ parcelle.producteur.prenoms }} sera supprimée définitivement,<br /> voulez-vous continuer ?</p>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <input type="submit" name="btnValider" value="Confirmer" id="btnValider" class="btn btn-primary" style="font-size:1.7vmin;" />
                                  <a href="{% url 'cooperatives:parcelles' %}" class="btn btn-danger" style="color: white">
                                       Annuler
                                  </a>
                            </div>
                        </div>
                    </form>
            </div>
        </div>
    </body>
</html>

cooperatives/templates/cooperatives/parcelles_data.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% include '_partials/css.html' %}
    <title>Mes Parcelles</title>
</head>
<body>

    {% block content %}
        <div class="container">
            <div class="row pt-5">
               <div class="col-sm-12 text-center">
                   <button class="btn btn-primary btn-get-data">
                       Charger Les Parcelles
                   </button>

                   <div class="content-data mt-4" data-url="{% url 'cooperatives:parcelles_data' %}">
                       Afficher Les données Ici.....
                   </div>
               </div>
            </div>
        </div>
    {% endblock %}


    {% include '_partials/js.html' %}
    <script>
        $('.btn-get-data').on('click', function(){
            $.ajax({
                 url: $('.content-data').data('url'),
                type: 'GET',
                dataType : 'json',
                success: function(){
                    $(".content-data").html(resp);
                },
                error: function(resp){
                    console.log('Une Erreure est Survenue Désolé...');
                }
            });
        });
    </script>
</body>
</html>

cooperatives/templates/cooperatives/section.html
<option value="">---------</option>
{% for section in coop_sections  %}
    <option value="{{ section.pk }}">{{ section.name }}</option>
{% endfor %}

cooperatives/templates/cooperatives/sous_section_delete.html
<!DOCTYPE html>
{% load static %}
{% load widget_tweaks %}
{% load bootstrap4 %}
{% bootstrap_messages %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Parheto10">
        <title>Agro - Map | Traçability</title>
        {% include '_partials/css.html' %}
        {% include '_partials/js.html' %}
        <script>
            $(document).ready(function(){
                $("#DeleteParcelleModal").modal('show');
            });
        </script>
    </head>
    <body>
        <div class="modal fade"  data-keyboard="false" data-backdrop="static" id="DeleteParcelleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
                <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="panel panel-red">
                            <div class="panel-heading">
                                <i class="fa fa-trash fa-fw"></i>  SUPPRESSION SOUS SECTION {{ item.libelle }} ({{ item.contacts }})
                            </div>
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-sm-12 text-center">
                                        <p style="font-size: 22px; font-weight: bold">la sous Section {{ item.libelle }}  sera supprimée définitivement,<br /> ainsi que les Producteurs Associés <br /> voulez-vous continuer ?</p>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <input type="submit" name="btnValider" value="Confirmer" id="btnValider" class="btn btn-primary" style="font-size:1.7vmin;" />
                                  <a href="{% url 'cooperatives:sous_sections' %}" class="btn btn-danger" style="color: white">
                                       Annuler
                                  </a>
                            </div>
                        </div>
                    </form>
            </div>
        </div>
    </body>
</html>

cooperatives/templates/cooperatives/sous_sections.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap4 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
{% block title %}
    Sous Sections |
{% endblock %}
{% block content %}
    <div id="wrapper">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    {% if user.is_authenticated %}
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'cooperatives:dashboard' %}">{{ cooperative.sigle }} / {{ cooperative.get_projet_values }}</a>
        </div>
    {% endif %}

    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>

    <ul class="nav navbar-right navbar-top-links">
        {% if user.is_authenticated %}
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> {{ user.username }} <b class="caret"></b>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out fa-fw"></i> Déconnexion</a>
                    </li>
                </ul>
            </li>
        {% endif %}
    </ul>
    <!-- /.navbar-top-links -->
    {% include 'cooperatives/coop_sidebar.html' %}
</nav>
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">Sous Sections</h1>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3">
                        {% include '_partials/messages_display.html' %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-info">
                            <div class="panel-heading">
                                <a href="{% url 'cooperatives:export_sous_section_xls' %}" class="btn btn-success"><i class="fa fa-download fa-fw"></i>Exporter En Excel</a>
                                <a href="#" class="btn btn-danger"> <i class="fa fa-file-pdf-o fa-fw">  </i>Exporter En PDF</a>
                                <button type="button" class="btn btn-primary pull-right" style="font-size:1.8vmin" data-toggle="modal" data-target="#agroModal" data-whatever="@mdo">
                                    Ajouter une Sous Section
                                </button>
                            </div>
                            <!-- /.panel-heading -->
                            <div class="panel-body" style="font-size: 14px">
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                        <thead class="text-center">
                                            <tr class="text-center">
                                                <th class="text-center">SECTION</th>
                                                <th class="text-center">LIBELLE</th>
                                                <th class="text-center">RESPONSABLE</th>
                                                <th class="text-center">CONTACTS</th>
                                                <th class="text-center">ACTIONS</th>
                                            </tr>
                                        </thead>
                                        <tbody class="text-center">
                                            {% for sous_section in sous_sections %}
                                                <tr class="odd gradeX">
                                                    <td class="center">{{ sous_section.section.libelle }}</td>
                                                    <td class="center">{{ sous_section.libelle }}</td>
                                                    <td class="center">{{ sous_section.responsable }}</td>
                                                    <td class="center">{% if sous_section.contacts %}{{ sous_section.contacts }}{% else %}{% endif %}</td>
                                                    <td>
                                                        <a href="#" onclick="edit('{% url 'cooperatives:edit_sous_section' sous_section.id %}')" style="padding: 3px;margin-top: 6px;" class="btn btn-primary">
                                                            <i class="fa fa-edit fa-fw"></i>
                                                        </a>
                                                        <a href="#" onclick="delete_semence('{% url 'cooperatives:delete_sous_section' sous_section.id %}')" style="padding: 3px;margin-top: 6px;" class="btn btn-danger">
                                                            <i class="fa fa-trash fa-fw"></i>
                                                        </a>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <!-- /.panel-body -->
                        </div>
                        <!-- /.panel -->
                    </div>
                    <!-- /.col-lg-8 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->

            <div class="modal fade"  data-keyboard="false" data-backdrop="static" id="agroModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg" role="document">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <i class="glyphicon glyphicon-plus" style="margin-bottom: 10px"></i> AJOUTER SOUS SECTION
                                    <button ID="btnAnnuler" type="button" data-dismiss="modal" class="btn btn-danger pull-right" style="font-size:1.8vmin; margin-top: -5px">
                                        <i class="fa fa-close"></i>
                                    </button>
                            </div>
                            <div class="panel-body">
                                <div class="col-sm-12">
                                    <div class="row">
                                        <div class="col-sm-12" style="margin-top: 25px">
                                            <div class="form-group">
                                                <label>SECTION</label>
                                              
{#                                                {% render_field parcelleForm.producteur class="form-control" %}#}
                                                <select name="section" placeholder="SECTION" class="form-control" id="id_section">
                                                    {% for section in sections %}
                                                        <option value="{{ section.id }}">{{ section.libelle }}</option>
                                                    {% endfor %}
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <label>LIBELLE</label>
                                                {% render_field form.libelle class="form-control" %}
                                            </div>
                                            <div class="form-group">
                                                <label>RESPONSABLE</label>
                                                {% render_field form.responsable class="form-control" %}
                                            </div>
                                            <div class="form-group">
                                                <label>CONTACTS</label>
                                                {% render_field form.contacts class="form-control CONTACT" maxlength="10" %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="panel-footer">
{#                                <Button ID="btnAnnuler" style="font-size:1.7vmin; width:100px" class="btn btn-default"  data-dismiss="modal" >Annuler</Button>#}
                                <input type="submit" name="btnValider" value="Valider" id="btnValider" class="btn btn-success btn-block" style="font-size:1.7vmin" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'js/function.js' %}"></script>
{% endblock %}