clients/urls.py
from django.urls import path

from .views import (
    DetailPlantings,
    client_index,
    coopdetailPlantings,
    detail_planting,
    export_formation_to_pdf,
    export_planting_xls,
    plants_par_section,
    projet,
    detail_proj,
    localisation,
    detail_coop,
    # chart,
    prod_coop,
    parcelle_coop,
    localisation_coop,
    section_coop,
    sous_section_coop,
    planting_coop, formations,
    detail_formation,
    export_prod_xls,
    export_parcelle_xls,
    export_prods_to_pdf,
    export_parcelles_to_pdf,
    Plantings, pepiniere, producteur, parcelle, production, planting, prod_coop_par_campagne,
    # export_plant_xls,
    # export_formation_xls,
    # export_prods_to_pdf,
    # export_parcelles_to_pdf,
    # producteursPDF
)

app_name = 'clients'

urlpatterns = [
    # path('', connexion, name='connexion'),
    # path('logout', loggout, name='logout'),
    path('index/', client_index, name='dashboard'), 
    path('projets/', projet, name='projets'),
    path('formation/<int:id>', formations, name='formations'),
    path('formation/<int:id>/<int:_id>', detail_formation, name='formation'),
    path('producteurs/<int:id>', prod_coop, name='prod_coop'),
    path('parcelles/<int:id>', parcelle_coop, name='parcelle_coop'),
    path('sections/<int:id>', section_coop, name='section_coop'),
    path('sous_sections/<int:id>', sous_section_coop, name='sous_section_coop'),
    path('planting/<int:id>', planting_coop, name='planting_coop'),
    path('coordonnes/<int:id>', localisation_coop, name='localisation_coop'),
    path('localisation/', localisation, name='localisation'),
    path('Plantings/', Plantings, name='Plantings'),
    path('DetailPlantings/', DetailPlantings, name='DetailPlantings'),
    path('coopdetailPlantings/<int:id>', coopdetailPlantings, name='coopdetailPlantings'),
    path('plants_par_section/<int:id>', plants_par_section, name='plants_par_section'),
    path('prod_coop_par_campagne/<int:id>', prod_coop_par_campagne, name='prod_coop_par_campagne'),

    # path('site_pepinieres/', site_pepinieres, name='site_pepinieres'),
    # path('coop_pepiniere/<int:id>', coop_pepiniere, name='coop_pepiniere'),
    path('detail_proj/<int:id>', detail_proj, name='detail_proj'),
    path('detail_coop/<int:id>', detail_coop, name='detail_coop'),
    # #Charts
    # path('Stats_coop/', Stats_coop, name='stats_coop'),
    # path('Stats_semences/', Stats_semences, name='stats_semences'),
    # path('Production_plan/', Production_plan, name='production_plan'),
    # path('plants_coop/<int:id>', plants_coop, name='plants_coop'),
    # path('semences_coop/<int:id>', semences_coop, name='semences_coop'),
    # path('chart/<int:id>', chart, name='chart'),
    #
    # #Export to Excel
    path('cooperative/<int:id>/producteurs/xls/', export_prod_xls, name='export_prod_xls'),
    # # path('sections/xls/', export_section_xls, name='export_section_xls'),
    # # path('sous_sections/xls/', export_sous_section_xls, name='export_sous_section_xls'),
    path('cooperative/<int:id>/parcelles/xls/', export_parcelle_xls, name='export_parcelle_xls'),
    # path('cooperative/<int:id>/plants/xls/', export_plant_xls, name='export_plant_xls'),
    # path('cooperative/<int:id>/formations/xls/', export_formation_xls, name='export_formation_xls'),
    #
    # # Export Données EN PDF
    path('producteurs/pdf/<str:id>', export_prods_to_pdf, name='export_prods_to_pdf'),
    # path('producteurs/pdf/<int:id>', producteursPDF, name='prods_to_pdf'),
    path('parcelles/pdf/<int:id>', export_parcelles_to_pdf, name='export_parcelles_to_pdf'),

    path('pepinieres/', pepiniere, name='pepinieres'),

    path('export_formation_to_pdf/<int:id>', export_formation_to_pdf, name='export_formation_to_pdf'),

    path('producteurs/', producteur, name='producteurs'),
    path('parcelles/', parcelle, name='parcelles'),
    path('productions/', production, name='productions'),
    path('plantings/', planting, name='plantings'),
    path('plantings/<str:code>', detail_planting, name='suivi_planting'),
    path('export_planting_xls/', export_planting_xls, name='export_planting_xls'),
]

traceability/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clients/', include('clients.urls')),
    path('cooperatives/', include('cooperatives.urls')),
    path('', include('parametres.urls')),
    # path('api/v1/', include('djoser.urls')),
    # path('api/v1/', include('djoser.urls.authtoken')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

clients/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os
import time
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
import datetime

from django.utils.safestring import mark_safe
#from django_countries.fields import CountryField

ANNEES = []
for r in range(2019, (datetime.datetime.now().year+1)):
    ANNEES.append((r,r))

def upload_logo_site(self, filename):
    # verification de l'extension
    real_name, extension = os.path.splitext(filename)
    name = str(int(time.time())) + extension
    return "logos/" + self.sigle + ".jpeg"

class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    sigle = models.CharField(max_length=500, verbose_name="NOM / SIGLE")
    contacts = models.CharField(max_length=50, verbose_name="CONTACTS")
    libelle = models.CharField(max_length=250, verbose_name="NOM")
    pays = models.CharField(max_length=250, verbose_name="NOM",default="")
    adresse = models.CharField(max_length=250, verbose_name="ADRESSE", blank=True)
    telephone1 = models.CharField(max_length=50)
    telephone2 = models.CharField(max_length=50, blank=True, null=True)
    email = models.EmailField(max_length=120, blank=True, verbose_name="ADRESSE EMAIL")
    siteweb = models.CharField(max_length=120, blank=True, verbose_name="SITE WEB")
    logo = models.ImageField(verbose_name="Logo", upload_to=upload_logo_site, blank=True)
    objects = models.Manager()

    def __str__(self):
        return '%s' % (self.libelle)

    def save(self, force_insert=False, force_update=False):
        self.sigle = self.sigle.upper()
        self.libelle = self.libelle.upper()
        super(Client, self).save(force_insert, force_update)

    class Meta:
        verbose_name_plural = "CLIENTS"
        verbose_name = "client"

    def Logo(self):
        if self.logo:
            return mark_safe('<img src="%s" style="width: 60px; height:50px;" />' % self.logo.url)
        else:
            return "Aucun Logo"

    Logo.short_description = 'Logo'

# Create your models here.

clients/views.py
import os
from itertools import product
import datetime
import xlwt
from django.db.models import Count
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login as dj_login, get_user_model, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User, Group
from django.contrib.staticfiles import finders
from django.core.mail import send_mail
from django.db.models import Sum
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.template.loader import get_template
from django.urls import reverse
# from django.utils.encoding import force_text
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
# from twisted.words.protocols.jabber.jstrports import client
#from xhtml2pdf import pisa
#from xhtml2pdf import pisa

from parametres.forms import PepiniereForm
from .models import Client
from parametres.models import (
    Sous_Prefecture,
    Origine,
    Prime,
    Projet,
    Activite,
    Region,
    Campagne, Cooperative, Pepiniere, Espece
)

from cooperatives.models import (
    Monitoring,
    MonitoringEspeceremplacement,
    Participantformation,
    Producteur,
    Parcelle,
    Planting,
    RemplacementMonitoring,
    Section,
    Sous_Section, Formation, Detail_Formation, DetailPlanting, Production
)


@login_required(login_url='connexion')
def client_index(request):
    cooperatives = Cooperative.objects.filter(utilisateur = request.user.utilisateur)
    production = 0
    petite_production = 0
    grande_production = 0
    nb_cooperatives = 0
    nb_parcelles = 0
    Superficie = 0
    nb_producteurs = 0
    Total_plant = 0

    for cooperative in cooperatives :
        
        if (Production.objects.filter(parcelle__producteur__cooperative_id=cooperative).aggregate(total=Sum('qteProduct'))['total']) != None: 
            production = production + (Production.objects.filter(parcelle__producteur__cooperative_id=cooperative).aggregate(total=Sum('qteProduct'))['total'])  
   
        if (Production.objects.filter(parcelle__producteur__cooperative_id=cooperative).filter(campagne="PETITE").aggregate(total=Sum('qteProduct'))['total']) != None :
            petite_production = petite_production + (Production.objects.filter(parcelle__producteur__cooperative_id=cooperative).filter(campagne="PETITE").aggregate(total=Sum('qteProduct'))['total']) 

        if (Production.objects.filter(parcelle__producteur__cooperative_id=cooperative).filter(campagne="GRANDE").aggregate(total=Sum('qteProduct'))['total']) != None :
            grande_production = grande_production + (Production.objects.filter(parcelle__producteur__cooperative_id=cooperative).filter(campagne="GRANDE").aggregate(total=Sum('qteProduct'))['total']) 

        AllCooperatives = Cooperative.objects.filter(id = cooperative.id)
        nb_producteurs = nb_producteurs + Producteur.objects.filter(cooperative_id=cooperative.id).count()
        prod_coop = Cooperative.objects.filter(id = cooperative.id).annotate(nb_producteur=Count('producteurs'))
        nb_cooperatives = nb_cooperatives + Cooperative.objects.filter(id = cooperative.id).count()
        section_coop = Cooperative.objects.filter(id = cooperative.id).annotate(nb_section=Count('sections'))
        nb_parcelles = nb_parcelles + Parcelle.objects.filter(producteur__cooperative=cooperative).count()
        if Parcelle.objects.filter(producteur__cooperative=cooperative).aggregate(total=Sum('superficie'))['total'] != None :
            Superficie = Superficie + Parcelle.objects.filter(producteur__cooperative=cooperative).aggregate(total=Sum('superficie'))['total']

        if Planting.objects.filter(parcelle__producteur__cooperative=cooperative).aggregate(total=Sum('plant_recus'))['total'] != None :
           Total_plant = Total_plant + Planting.objects.filter(parcelle__producteur__cooperative_id=cooperative).aggregate(total=Sum('plant_recus'))['total']



    production = production /1000
    petite_production = petite_production /1000
    grande_production = grande_production /1000
    
    
    
    


    if len(cooperatives) > 1 :
        for coop in cooperatives:
            coop.parcelles =  Parcelle.objects.filter(producteur__cooperative=coop).count()
            coop.productions = Production.objects.filter(parcelle__producteur__cooperative=coop).aggregate(total=Sum('qteProduct'))['total']
            coop.plants = Planting.objects.filter(parcelle__producteur__cooperative=coop).aggregate(total=Sum('plant_recus'))['total']
            coop.superficies = Parcelle.objects.filter(producteur__cooperative=coop).aggregate(total=Sum('superficie'))[ 'total']

    elif len(cooperatives) == 1 :
        cooperatives.parcelles = Parcelle.objects.filter(producteur__cooperative__utilisateur=request.user.utilisateur).count()
        cooperatives.productions = Production.objects.filter(parcelle__producteur__cooperative__utilisateur=request.user.utilisateur).aggregate(total=Sum('qteProduct'))['total']
        cooperatives.plants = Planting.objects.filter(parcelle__producteur__cooperative__utilisateur=request.user.utilisateur).aggregate(total=Sum('plant_recus'))['total']
        cooperatives.superficies = Parcelle.objects.filter(producteur__cooperative__utilisateur=request.user.utilisateur).aggregate(total=Sum('superficie'))[ 'total']


    context = {
        'cooperatives': cooperatives,
        'AllCooperatives': AllCooperatives,
        'nb_cooperatives': nb_cooperatives,
        'nb_producteurs': nb_producteurs,
        'nb_parcelles': nb_parcelles,
        'Superficie': Superficie,
        'Total_plant': Total_plant,
        'prod_coop': prod_coop,
        'section_coop': section_coop,
        'production': production,
        'petite_production': petite_production,
        'grande_production': grande_production,
        # 'activate': activate
        # 'section_cooperative': section_cooperative,
    }
    return render(request, 'clients/index.html', context)


@login_required(login_url='connexion')
def detail_coop(request, id=None):
    activate = "dashboard"
    cooperative = get_object_or_404(Cooperative, id=id)
    # coop_nb_producteurs =
    section = Section.objects.filter(cooperative_id=cooperative)
    sous_sections = Sous_Section.objects.filter(section__cooperative_id=cooperative)
    # section_prod = Producteur.objects.all().filter(section_id__in=section).count()
    section_prod = Section.objects.annotate(nb_producteur=Count('producteurs'))
    prod_section = Producteur.objects.filter(section_id__in=section).count()
    coop_nb_producteurs = Producteur.objects.filter(cooperative_id=cooperative).count()
    nb_formations = Formation.objects.filter(cooperative_id=cooperative).count()
    parcelles_section = Parcelle.objects.filter(producteur__section_id__in=section).count()
    # section_parcelle = Section.objects.annotate(nb_producteur=Count('producteurs.parcelles'))
    coop_nb_parcelles = Parcelle.objects.filter(producteur__cooperative_id=cooperative).count()
    coop_superficie = Parcelle.objects.filter(producteur__cooperative_id=cooperative).aggregate(total=Sum('superficie'))['total']
    section_superf = Parcelle.objects.filter(producteur__section_id__in=section).aggregate(total=Sum('superficie'))['total']
    coop_plants_total = DetailPlanting.objects.filter(planting__parcelle__producteur__cooperative_id=cooperative).aggregate( total=Sum('nb_plante'))['total']

    production = 0
    petite_production = 0
    grande_production = 0
    
    if (Production.objects.filter(parcelle__producteur__cooperative_id=cooperative).aggregate(total=Sum('qteProduct'))['total']) != None: 
        production = production + (Production.objects.filter(parcelle__producteur__cooperative_id=cooperative).aggregate(total=Sum('qteProduct'))['total'])  
   
    if (Production.objects.filter(parcelle__producteur__cooperative_id=cooperative).filter(campagne="PETITE").aggregate(total=Sum('qteProduct'))['total']) != None :
        petite_production = petite_production + (Production.objects.filter(parcelle__producteur__cooperative_id=cooperative).filter(campagne="PETITE").aggregate(total=Sum('qteProduct'))['total']) 

    if (Production.objects.filter(parcelle__producteur__cooperative_id=cooperative).filter(campagne="GRANDE").aggregate(total=Sum('qteProduct'))['total']) != None :
        grande_production = grande_production + (Production.objects.filter(parcelle__producteur__cooperative_id=cooperative).filter(campagne="GRANDE").aggregate(total=Sum('qteProduct'))['total']) 

    context = {
        'cooperative': cooperative,
        'coop_nb_producteurs': coop_nb_producteurs,
        'coop_nb_parcelles': coop_nb_parcelles,
        'coop_superficie': coop_superficie,
        'nb_formations': nb_formations,
        'section': section,
        'sous_sections': sous_sections,
        'prod_section': prod_section,
        'section_prod': section_prod,
        # 'section_parcelle': section_parcelle,
        'parcelles_section': parcelles_section,
        'coop_plants_total': coop_plants_total,
        'section_superf': section_superf,
        'production': production,
        'petite_production': petite_production,
        'grande_production': grande_production,
        'activate': activate
        # 'labels': labels,
        # 'data': data,
    }
    return render(request, 'clients/Coop/cooperative.html', context)

# @login_required(login_url='connexion')
# def detail_coop(request, id=None):
#     activate = "dashboard"
#     cooperative = get_object_or_404(Cooperative, id=id)
#     # coop_nb_producteurs =
#     section = Section.objects.filter(cooperative_id=cooperative)
#     sous_sections = Sous_Section.objects.filter(section__cooperative_id=cooperative)

clients/templates/clients/client_nav.html
{% load static %}

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="navbar-header">
        {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'clients:dashboard' %}">PANNEAU D'ADMINISTRATION - {{ user.username }}</a>
        {% endif %}
    </div>

    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>

    <ul class="nav navbar-right navbar-top-links">
        {% if user.is_authenticated %}
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw" style="font-size: 18px; font-weight: bold"></i> {{ user.username }} <b class="caret"></b>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out fa-fw"></i> Déconnexion</a>
                    </li>
                </ul>
            </li>
        {% endif %}

       
    </ul>
{#    <div class="col-sm-6" style="text-align-last: end">#}
{#        <select id="monselect" style="text-align: center">#}
{#          <option value="Français" selected>Fr</option>#}
{#          <option value="Anglais">Ang</option>#}
{#        </select>#}
{#    </div>#}
    <!-- /.navbar-top-links -->
    {% include 'clients/client_sidebar.html' %}
</nav>

clients/templates/clients/client_sidebar.html
{% load static %}
<style>
    .sidebar ul li a.active {
    background-color: #b4b4b4;
}
</style>
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li>
                <a href="{% url 'clients:dashboard' %}" {% if activate == "dashboard" %}class="active"{% else %} class="" {% endif %}><i class="fa fa-dashboard fa-fw"></i> DASHBOARD</a>
            </li>
            <li>
{#                <a href="{% url 'clients:projets' %}" class="active"><i class="fa fa-dashboard fa-fw"></i> GESTION PROJETS</a>#}
            </li>
         
            <li>
                <a href="{% url 'clients:producteurs' %}" {% if activate == "pepiniere" %}class="active"{% else %} class="" {% endif %}><i class="fa fa-users fa-fw"></i> GESTION PRODUCTEURS</a>
            </li>
            <li>
                <a href="{% url 'clients:parcelles' %}" {% if activate == "pepiniere" %}class="active"{% else %} class="" {% endif %}><i class="fa fa-map" aria-hidden="true"></i> GESTION PARCELLES</a>
            </li>
            <li>
                <a href="{% url 'clients:plantings' %}" {% if activate == "pepiniere" %}class="active"{% else %} class="" {% endif %}><i class="fa fa-tree" aria-hidden="true"></i> GESTION PLANTINGS</a>
            </li>
            <li>
                <a href="{% url 'clients:productions' %}" {% if activate == "pepiniere" %}class="active"{% else %} class="" {% endif %}><i class="fa fa-cubes" aria-hidden="true"></i> GESTION PRODUCTIONS</a>
            </li>
            <li>
                <a href="{% url 'catre_parcelles' %}" target="_blank"><i class="fa fa-map-marker fa-fw"></i>CARTE PARCELLES</a>
            </li>

            <li>
                <a href="{% url 'catre_pepiniere' %}" target="_blank"><i class="fa fa-map-pin" aria-hidden="true"></i> CARTE PEPINIERES</a>
            </li>
            <li>
                {#                  <a href="#" target="_blank"><i class="fa fa-map-marker fa-fw"></i> PLANTINGS</a>#}
            </li>
        </ul>
    </div>
</div>

clients/templates/clients/parcelles.html
{% extends 'base.html' %}
{% block title %}
    Parcelles |
{% endblock %}
{% block content %}
    <div id="wrapper">
            <!-- Navigation -->
            {% include 'clients/client_nav.html' %}
            <div id="page-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <h1 class="page-header"><i class="fa fa-users fa-fw"></i> PARCELES</h1>
                        </div>
                        <!-- /.col-lg-12 -->
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-primary">
                                <div class="panel-heading">
                                    <i class="fa fa-map" aria-hidden="true"></i> PARCELES
                                </div>
                                <!-- /.panel-heading -->
                                <div class="panel-body">
                                    <div class="table-responsive">
                                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                            <thead>
                                                <tr>
                                                    <th class="text-center">COOPERATIVE</th>
                                                    <th class="text-center">SECTION</th>
                                                    <th class="text-center">PRODUCTEUR</th>
                                                    <th class="text-center">CODE CERTIF</th>
                                                    <th class="text-center">CODE PARCELLE</th>
                                                    <th class="text-center">LOCALITE</th>
                                                    <th class="text-center">COORDONNEES</th>
                                                    <th class="text-center">SUPERFICIE (Ha)</th>
                                                    <th class="text-center">PLANTS RECUS</th>
                                                    <th class="text-center">PLANTS PLANTES</th>
{#                                                    <th>ACTIONS</th>#}
                                                </tr>
                                            </thead>
                                            <tbody class="text-center">
                                                {% for p in parcelles %}
                                                    <tr class="odd gradeX text-center">
                                                        <td>{{ p.producteur.cooperative.sigle }}</td>
                                                        <td>{{ p.producteur.section.libelle }}</td>
                                                        <td>{{ p.producteur.nom }}</td>
                                                        {% if p.code_certificat %}
                                                            <td>{{ p.code_certificat }}</td>
                                                        {% else %}
                                                            <td class="center"><b class="text-danger text-center">PAS RENSEIGNER</b></td>
                                                        {% endif %}
                                                        <td>{{ p.code }}</td>
                                                        <td>{{ p.producteur.localite }}</td>
                                                        <td>{{ p.coordonnees }}</td>
                                                        <td>{{ p.superficie | floatformat:2 }}</td>
                                                        {% if p.plants_recus is None%}<td></td>{% else %}<td>{{ p.plants_recus }}</td>{% endif %}
                                                        {% if p.plants_plante is None %}<td></td>{% else %}<td>{{ p.plants_plante }}</td>{% endif %}
{#                                                        <td class="center">{{ prod.parcelles.all|length }}</td>#}
{#                                                        <td class="center">{{ prod.superficies | floatformat:2 }}</td>#}
{#                                                        <td class="center"><a href="{% url 'detail_coop' coop.pk %}" class="btn btn-primary btn-xs">Accéder</a></td>#}
                                                    </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <!-- /.panel-body -->
                            </div>
                            <!-- /.panel -->
                        </div>
                        <!-- /.col-lg-8 -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- /#page-wrapper -->
        </div>
{% endblock %}

clients/templates/clients/producteurs.html
{% extends 'base.html' %}
{% block title %}
    Producteurs |
{% endblock %}
{% block content %}
    <div id="wrapper">
            <!-- Navigation -->
            {% include 'clients/client_nav.html' %}
            <div id="page-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <h1 class="page-header"><i class="fa fa-users fa-fw"></i> PRODUCTEURS</h1>
                        </div>
                        <!-- /.col-lg-12 -->
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-primary">
                                <div class="panel-heading">
                                    <i class="fa fa-home" aria-hidden="true"></i> PRODUCTEURS
                                </div>
                                <!-- /.panel-heading -->
                                <div class="panel-body">
                                    <div class="table-responsive">
                                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                            <thead>
                                                <tr>
                                                    <th class="text-center">COOPERATIVE</th>
                                                    <th class="text-center">SECTION</th>
                                                    <th class="text-center">NOM</th>
                                                    <th class="text-center">LOCALITE</th>
                                                    <th class="text-center">CONTACTS</th>
                                                    <th class="text-center">NRE PARCELLES</th>
                                                    <th class="text-center">SUPERFICIE (Ha)</th>
{#                                                    <th>ACTIONS</th>#}
                                                </tr>
                                            </thead>
                                            <tbody class="text-center">
                                                {% for prod in producteurs %}
                                                    <tr class="odd gradeX text-center">
                                                        <td>{{ prod.cooperative.sigle }}</td>
                                                        <td>{{ prod.section.libelle }}</td>
                                                        <td>{{ prod.nom }}</td>
                                                        <td class="center">{{ prod.localite }}</td>
                                                        {% if prod.contacts != 'null' %}
                                                            <td class="center">{{ prod.contacts }}</td>
                                                        {% else %}
                                                            <td class="center"><b class="text-danger text-center">AUCUN CONTACT</b></td>
                                                        {% endif %}
                                                        <td class="center">{{ prod.parcelles.all|length }}</td>
                                                        <td class="center">{{ prod.superficies | floatformat:2 }}</td>
{#                                                        <td class="center"><a href="{% url 'detail_coop' coop.pk %}" class="btn btn-primary btn-xs">Accéder</a></td>#}
                                                    </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <!-- /.panel-body -->
                            </div>
                            <!-- /.panel -->
                        </div>
                        <!-- /.col-lg-8 -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- /#page-wrapper -->
        </div>
{% endblock %}